[package]
name = "client"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
#egui.workspace = true
#eframe.workspace = true
log.workspace = true
simplelog.workspace = true
jni = "0.21.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.135"